### ISSUE TITLE
Execute raises ValueError

### ISSUE THREAD

**Issue by franklin216** [tnesztler/bamboorules#1]
Hello, 

i don't know if i did not understand the library correctly, but if i try to execute a filter on a Dataframe, there is a ValueError. 

Can you help me with this?

Best regards 

           cars = {'Brand': ['Honda Civic', 'Toyota Corolla', 'Ford Focus', 'Audi A4'],
                    'Price': [22000, 25000, 27000, 35000]
                    }

            df = pd.DataFrame(cars, columns=['Brand', 'Price'])
            print(df)
            en = engine.Engine()
            logic_rules = {"<": [{"var": "Price"}, 27000]}

            filterd_df = en.execute(logic_rules,df)
            print(filterd_df)

Raises following Error
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**Comment by tnesztler** [comment]
Hi @franklin216,

Keep in mind this library is still in active development, however, I've attached a working example.
You can pass multiple variables through the `data` dictionary/kwarg, so `df` must be part of it.
Getting a "column" / series out of the DataFrame, requires the `get` method.

```
cars = {
    'Brand': ['Honda Civic', 'Toyota Corolla', 'Ford Focus', 'Audi A4'],
    'Price': [22000, 25000, 27000, 35000]
}
df = pd.DataFrame(cars, columns=['Brand', 'Price'])
print(df)
en = engine.Engine()
logic_rules = {"<": [{"get": [{"var": "df"}, "Price"]}, 27000]}
filtered_df = en.execute(logic_rules, {"df": df})
print(filtered_df)
```

**Comment by franklin216** [comment]
Thank you for this example. It works great :-)
